# XDG
export XDG_CONFIG_HOME=$HOME/.config
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"

# editor
export EDITOR="hx"
export VISUAL="hx"

# Man pages
export MANPAGER="nvim +Man!"

# fzf
export FZF_DEFAULT_COMMAND="rg --files --hidden --glob '!.git'"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"


FZF_COLORS="bg+:-1,\
fg:gray,\
fg+:white,\
border:black,\
spinner:0,\
hl:yellow,\
header:blue,\
info:green,\
pointer:red,\
marker:blue,\
prompt:gray,\
hl+:red"

export FZF_DEFAULT_OPTS="--height 60% \
--border sharp \
--layout reverse \
--color '$FZF_COLORS' \
--prompt '∷ ' \
--pointer ▶ \
--marker ⇒"



# PATH
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$HOME/go/bin:$PATH"
export PATH="/opt/homebrew/bin:$PATH"

export DATABASE_URL="postgresql://postgres:postgres@localhost:5432/sunkbar"

# Elixir & Phoenix Framework
export PATH=$HOME//opt/homebrew/Cellar/erlang/27.2.1/lib/erlang/erts-15.2.1/bin:$PATH
export PATH=$HOME//opt/homebrew/bin:$PATH
