[Posteo]
source        = notmuch://~/mail
check-mail-cmd = ./mail-sync.sh
check-mail = 2m
check-mail-timeout = 30s
outgoing      = smtps://enas%40posteo.com@posteo.de:465
outgoing-cred-cmd = "security find-generic-password -a enas@posteo.com -s mbsync -w"
default       = Inbox
archive       = posteo/Archive
folders-sort  = Inbox,Unread,Flagged,Sent,Drafts,Archive,Spam,Trash
folders-exclude = posteo/Inbox,posteo/Archive,posteo/Drafts,posteo/Sent,posteo/Spam,posteo/Trash
from          = Erik Naslund <erik.naslund@posteo.com>
maildir-store = ~/mail
query-map     = ~/.config/aerc/Posteo.qmap
