#
# aerc main configuration

[general]
default-save-path=~/Downloads
log-file=~/.aerc.log

[ui]
styleset-name=base16_term
fuzzy-complete=true
completion-delay=250ms
completion-min-chars=1

[statusline]

[viewer]
alternatives=text/plain,text/html
header-layout=From,To,Cc,Bcc,Date,Subject

# Parses and extracts http links when viewing a message. Links can then be
# accessed with the open-link command.
#
# Default: true
#parse-http-links=true

[compose]
header-layout=From,To,Cc,Subject
address-book-cmd='notmuch address "%s"'
reply-to-self=false
empty-subject-warning=true

no-attachment-warning=^[^>]*(?:attach(ed|ment)|bifoga(?:t|d|de))

[multipart-converters]
#
# Converters allow to generate multipart/alternative messages by converting the
# main text/plain part into any other MIME type. Only exact MIME types are
# accepted. The commands are invoked with sh -c and are expected to output
# valid UTF-8 text.
#
# Example (obviously, this requires that you write your main text/plain body
# using the markdown syntax):
#text/html=pandoc -f markdown -t html --standalone

[filters]
text/plain=colorize
text/calendar=calendar
message/delivery-status=colorize
message/rfc822=colorize
text/rfc822-headers=colorize
text/html=! w3m -T text/html -I UTF-8
.headers=colorize
application/pdf=pdftotext - -

[openers]

[hooks]

[templates]
