unbind C-b
set -g prefix M-Space
bind M-Space send-prefix

set-window-option -g mode-keys vi
set -g mouse on

set-option -sa terminal-overrides ",xterm*:Tc"

set -g base-index 1
setw -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on


bind-key -T prefix h select-window -p
bind-key -T prefix l select-window -n
bind-key -T prefix Tab switch-client -T windows
bind-key -T prefix w switch-client -T pane
bind-key -T prefix y switch-client -T copy-mode

bind-key -T pane d split-window -v -c "#{pane_current_path}"
bind-key -T pane s split-window -h -c "#{pane_current_path}"
bind-key -T pane h select-pane -L
bind-key -T pane j select-pane -D
bind-key -T pane k select-pane -U
bind-key -T pane l select-pane -R
bind-key -T pane f resize-pane -Z
bind-key -T pane . switch-client -T pane-resize

bind-key -T root M-h select-pane -L
bind-key -T root M-j select-pane -D
bind-key -T root M-k select-pane -U
bind-key -T root M-l select-pane -R

bind-key -T pane-resize c resize-pane -L 5\; switch-client -T pane-resize
bind-key -T pane-resize t resize-pane -D 5\; switch-client -T pane-resize
bind-key -T pane-resize s resize-pane -U 5\; switch-client -T pane-resize
bind-key -T pane-resize r resize-pane -R 5\; switch-client -T pane-resize
bind-key -T pane-resize C resize-pane -L\; switch-client -T pane-resize
bind-key -T pane-resize T resize-pane -D\; switch-client -T pane-resize
bind-key -T pane-resize S resize-pane -U\; switch-client -T pane-resize
bind-key -T pane-resize R resize-pane -R\; switch-client -T pane-resize

bind-key -T windows c new-window
bind-key -T windows n next-window
bind-key -T windows p previous-window

set -g status-right " #{client_key_table} "

bind-key -T root M-0 select-window -t 0
bind-key -T root M-1 select-window -t 1
bind-key -T root M-2 select-window -t 2
bind-key -T root M-3 select-window -t 3
bind-key -T root M-4 select-window -t 4
bind-key -T root M-5 select-window -t 5
bind-key -T root M-6 select-window -t 6
bind-key -T root M-7 select-window -t 7
bind-key -T root M-8 select-window -t 8
bind-key -T root M-9 select-window -t 9

