# Themes can be found at https://github.com/alacritty/alacritty-theme
# I prefer to keep a local copy of the theme next to the .dotfile.
# It is a bit redundant, but it makes the .config plug and play
import = ["~/.config/alacritty/theme.toml"]

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"
option_as_alt = "OnlyLeft"


[font]
normal.family = "TX-02"
bold.family = "TX-02"
italic.family = "TX-02"
bold_italic.family = "TX-02"

size = 16.0
